# -*- coding: utf-8 -*-
"""IA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDQx3SswXoWWWgD-RSRoLC_qPGvkvDju

1
"""

l=int(input("Enter the length(in m): "))
b=int(input("Enter the breadth(in m): "))
print("Area of the rectangle(in m): ",l*b)

"""2"""

w=int(input("Enter the weight in kg:"))
h=float(input("Enter the height in m:"))
print("BMI of the user is: ",(w/(h**2)))

"""3"""

d={}
while 1:
  n=input(("Do you want to enter info?(Y/N)"))
  if(n.lower()=="y"):
    name=input("Enter the name: ")
    marks=int(input("Enter the marks: "))
    d[name]=marks
  else:
    break
for key,value in d.items():
  print(key," has scored ",value)

"""4"""

while 1:
  n=input(("Do you want to enter info?(Y/N)"))
  if(n.lower()=="y"):
    age=int(input("Enter the age: "))
    if age<18:
      print("The user is minor")
    elif age<60:
      print("The user is adult")
    else:
      print("The user is senior")
  else:
    break

"""5"""

for i in range(1,51):
  if i%2==0:
    print(i)

"""6"""

pw=["hello","world","python","program"]
while 1:
  n=input(("Enter the password: "))
  if n in pw:
    print("Correct password")
    break
  else:
    print("Password is wrong.Please re-enter.")

"""7"""

l=[]
n=int(input("Enter the size of list: "))
for i in range(n):
  x=int(input("Enter value: "))
  l.append(x)
sum=0
for i in range(n):
  sum=sum+l[i]
print("The average is: ",sum/len(l))

"""8"""

def vowels(s):
  ct=0
  for i in range(len(s)):
    if s[i]=='a' or s[i]=='e' or s[i]=='i' or s[i]=='o' or s[i]=='u' or s[i]=='A' or s[i]=='E' or s[i]=='I' or s[i]=='O' or s[i]=='U':
      ct=ct+1
  return ct
st=input("Enter a string:")
print("The total number of vowels are: ",vowels(st))

"""9"""

from datetime import date
print("Current date:", date.today())
print("Current time: ",date.now())

"""10"""

try:
  x=1+s
  print(x)
except:
  print("Integer value is not inserted while addition")

"""11"""

try:
  x=int(input("Enter an integer: "))
except ValueError:
  print("ERROR!Integer is not inserted")

"""12"""

try:
  y=int(input("Enter a integer: "))
  z=int(input("Enter a integer: "))
  x=y/z
  print(x)
except :
  print("ERROR!Integer is divided by zero")

"""13"""

f=open('/content/Write.txt','w')
f.writelines("Hello, Python")
print("Contents are written into the file")
f.close()

"""14"""

f=open('/content/Write.txt','r')
x=f.read()
print(x)
f.close()

"""15"""

f=open('/content/Write.txt','w')
f.writelines("Hello, World")
print("Contents are written into the file")
f.close()
f=open('/content/Write.txt','r')
x=f.read()
print(x)
f.close()