# -*- coding: utf-8 -*-
"""IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123Vc6KKd_uINbEopY3gTc682UyJa5qew

1
"""

import numpy as np
import pandas as pd
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],
                    [[255,255,0],[255,0,255],[0,255,255]],
                    [[127,127,127],[200,200,200],[50,50,50]]])
for i in rgb_image:
  for j in i:
    print(j[0]*0.2989+j[1]*0.5870+j[2]*0.1140)

"""2"""

data=np.array([[172,68,22],
              [189,54,30],
              [150,60,24]])

for i in data:
  print(i.std())
  print(i.mean())

"""3"""

data=np.array([[1,2,3],[4,5,6]],ndmin=3)
print('3D array',data)
data=data.flatten()
print('Flattened data:',data)
data=np.array(data,ndmin=2)
print('Flattened data in 2D array: ',data)

"""4"""

data=np.array([[1,9,10],
              [2,10,10],
              [3,8,7]])
print(data)

for i in data:
  print('The percentage improvement for player ',i[0] ,' is',((i[2]-i[1])/i[1])*100)

"""5"""

data={'Name':['A','B','C'],'Maths':[100,78,96],'English':[45,-1,89],'EVS':[-1,78,90]}
df=pd.DataFrame(data).T

df=df.replace(-1,0)
print(df)

"""6"""

data=np.array([['1',10,30],
              ['2',2,40],
              ['3',3,50]])
for i in data:
  for j in i:
    if i[1]==2:
      i[2]+=10
    else:
      pass
print(data)

"""7"""

data={'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
      'Age':[25,30,35,40,45,50,55],
      'City':['New York','Los Angels','Chicago','Houston','Phoenix','Miami','Boston'],
      'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']}
df=pd.DataFrame(data)

filter=df[(df['Age']<45) & (df['Department']!='HR')][['Name','City']]
print(filter)

"""8"""

data={'Product':['Apples','Bananas','Cherries','Dates','Elderberries','Flour','Grapes'],
      'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit'],
      'Price':[1.20,0.50,3.00,2.50,4.00,1.50,2.00],
      'Promotion':[True,False,True,True,False,True,False]}
df=pd.DataFrame(data)
print(df)
filter1=df[(df['Category']=='Fruit')]
avg=[filter1.groupby('Category')['Price'].mean()]
print(filter1)
print(avg)
for i,j in avg:
  filter2=filter1[((filter1['Price']>j) & (filter['Promotion'])==False)]
print(filter2)

"""9"""

data1={'Employee':['Alice','Bob','Charlie','David'],
       'Department':['HR','IT','Finance','IT'],
       'Manager':['John','Rachel','Emily','Rachel']}
data2={'Employee':['Alice','Charlie','Eve'],
       'Project':['P1','P3','P2']}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
df3=df.merge(df1,df2,on='Employee',how='left')
print(df3)

"""10"""

data1={'Departement':['Electronics','Electronics','Clothing','Clothing','Home Goods'],
       'Salesperson':['Alice','Bob','Charlie','David','Eve'],
       'Sales':[70000,50000,30000,40000,60000]}
df=pd.DataFrame(data1)

filter=df.groupby('Salesperson')['Sales'].mean()
print(filter)