# -*- coding: utf-8 -*-
"""lvadudsr_79_ChrisSasanDoss_lab4.ipynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nyej3-FTOYYMqx08r9Q6mJYX2kE6enjY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import mean_squared_error, accuracy_score, confusion_matrix, recall_score, f1_score, precision_score,silhouette_score, davies_bouldin_score, calinski_harabasz_score,mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings("ignore")

"""Read Data"""

df=pd.read_csv('/content/social_network.csv')
print(df)

#Handling null values and duplicates
n=df.isnull().sum()
print('Null values in the dataset:\n',n)
dd=df[df.duplicated()]
print('Duplicate rows in the datset:\n',dd)

#Handling outliers
plt.figure(figsize=(20,15))
sns.boxplot(df)
plt.show()
#No outliers found

"""EDA"""

#Describing Data
print('Head of the dataset:\n',df.head())
print('Tail of the dataset:\n',df.tail())
print('Description of the dataset:\n',df.describe())
print('Columns of the dataset:\n',df.columns)
print('Shape of the data:\n',df.shape)
print('Correleation of features:\n',df.corr())

#Viz
sns.heatmap(df.corr())
plt.show()

from matplotlib import pyplot as plt
df['login_activity'].plot(kind='hist', bins=20, title='login_activity')
plt.show()

df.groupby('account_status').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.show()


def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['user_id']
  ys = series['login_activity']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('user_id', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('account_status')):
  _plot_series(series, series_name, i)
  fig.legend(title='account_status', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('user_id')
_ = plt.ylabel('login_activity')
plt.show()

"""Model Training"""

ml=IsolationForest()
fit=ml.fit(df[['login_activity','social_connections']])
op=ml.predict(df[['login_activity','social_connections']])
l=[]
for i in op:
  if i==-1:
    l.append('Anomaly')
  if i==1:
    l.append('Not Anomaly')
df['Result']=l
a=df[df['Result']=='Anomaly']
n=df[df['Result']=='Not Anomaly']
plt.scatter(a['login_activity'],a['social_connections'],label='Anomaly',color='r')
plt.scatter(n['login_activity'],n['social_connections'],label='Not Anomaly')
plt.xlabel('Login Activity')
plt.ylabel('Social Connections')
plt.legend()
plt.title('Anomaly Detection')

"""Model Evaluation"""

print('Inliners:\n',df[df['Result']=='Not Anomaly'])
print('Outliers:\n',df[df['Result']=='Anomaly'])