# -*- coding: utf-8 -*-
"""lvadudsr_79_ChrisSasanDoss_lab2.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z_sa4nsYSFcxyc8nq9DCYFzBkI9CpmPm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import mean_squared_error, accuracy_score, confusion_matrix, recall_score, f1_score, precision_score,silhouette_score, davies_bouldin_score, calinski_harabasz_score,mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings("ignore")

"""Read Data"""

df=pd.read_csv('/content/auto-mpg.csv')
print(df)

"""Data Processing"""

#Handling null values and duplicates
n=df.isnull().sum()
print('Null values in the dataset:\n',n)
df=df.dropna()
dd=df[df.duplicated()]
print('Duplicate rows in the datset:\n',dd)
df=df[df['horsepower']!='?']

#Handling outliers
plt.figure(figsize=(20,15))
sns.boxplot(df)
plt.show()

q1=df['acceleration'].quantile(0.25)
q3=df['acceleration'].quantile(0.75)
iqr=q3-q1
l_limit=q1-(iqr*1.5)
u_limit=q3+(iqr*1.5)
df=df[(df['acceleration']>l_limit) & (df['acceleration']<u_limit)]

"""EDA"""

#Describing Data
print('Head of the dataset:\n',df.head())
print('Tail of the dataset:\n',df.tail())
print('Description of the dataset:\n',df.describe())
print('Columns of the dataset:\n',df.columns)
print('Shape of the data:\n',df.shape)
print('Correleation of features:\n',df.corr())

#Viz
sns.heatmap(df.corr())
plt.show()

df.plot(kind='scatter', x='weight', y='acceleration', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.show()

df['mpg'].plot(kind='hist', bins=20, title='mpg')
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.show()

df['cylinders'].plot(kind='hist', bins=20, title='cylinders')
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.show()

"""Model Training"""

#Encoding categorical variables
lb=LabelEncoder()
df['car name']=lb.fit_transform(df['car name'])


#Model dev
x=df.drop(columns=['model year','car name','mpg'])
y=df['mpg']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
ml=LinearRegression()
fit=ml.fit(x_train,y_train)
op=ml.predict(x_test)
print(op)

"""Model Evaluation"""

cvs=cross_val_score(ml,x_train,y_train,cv=5)
mea=mean_absolute_error(y_test,op)
mse=mean_squared_error(y_test,op)
rmse=mean_squared_error(y_test,op,squared=False)
r=r2_score(y_test,op)
print('Mean Squared Error:',mse)
print('\nMean Absolute Error:',mea)
print('\nRoot Mean Square Error:',rmse)
print('\nCross validation score:',cvs)
print('\nMean of cross validation score:',cvs.mean())